version: '3.7'

volumes:
  data-db:

services:

  db:
    image: postgres:10.3
    expose:
      - 5432
    volumes:
      - ./postgres:/opt/postgres
      - data-db:/var/lib/postgresql/data
    environment:
      # TODO: change this password, currently checked into git
      POSTGRES_PASSWORD: A224697C73DDC7439E35E7272909246D0AB8E5BBE
      POSTGRES_USER: gitsu
      POSTGRES_DB: gitsu


  # Service for Analytics
  # analytics:
  #   build: 
  #     context: analytics/.
  #     dockerfile: Dockerfile-dev 
  #   volumes:
  #     - ./analytics:/opt/analytics
  #     - ./:/opt/gitsu_root
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     - db
  #   environment:
  #     JUPYTER_CONFIG_DIR: '/opt/analytics/'       
  #     JUPYTER_PASSWORD: 'abc123'    
  #     JUPYTER_ENABLE_LAB: 'yes'
  #     CONFIG_FILES: 'base.yaml:/opt/gitsu_root/local_settings.yaml'


  # Service for ETL using Airflow
  etl:
    build: 
      context: etl/.
    volumes:
      - ./etl:/usr/src/app
      - ./:/opt/jiu_gitsu_root
    depends_on:
      - db
    environment:
      CONFIG_FILES: 'base.yaml:/opt/jiu_gitsu_root/local_settings.yaml'
      # TODO: change this password, currently checked into git
      POSTGRES_PASSWORD: A224697C73DDC7439E35E7272909246D0AB8E5BBE
      POSTGRES_USER: gitsu
      POSTGRES_DB: gitsu
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
        - "8080:8080"


  # # Service for Analytics
  # gitsu_web:
  #   build: ./gitsu_web/.
  #   volumes:
  #     - ./gitsu_web/src:/go/src
  #   command: watcher -run main
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   links:
  #     - db
