version: '3.1'

services:

  db:
    image: postgres:10.3
    expose:
      - 5432
    volumes:
      - ./postgresql/scripts:/opt/postgresql/scripts
    environment:
      # TODO: change this password, currently checked into git
      POSTGRES_PASSWORD: A224697C73DDC7439E35E7272909246D0AB8E5BBE
      POSTGRES_USER: gitsu
      POSTGRES_DB: gitsu

  # Service for ETL
  gitsu:
    build: ./gitsu/.
    volumes:
      - ./:/opt/gitsu
    depends_on:
      - db
    links:
      - db

  # Service for Analytics
  gitsu_analytics:
    build: ./gitsu_analytics/.
    volumes:
      - ./gitsu_analytics:/opt/gitsu_analytics
      - ./:/opt/gitsu
    ports:
      - 8888:8888
    depends_on:
      - db
    links:
      - db
    environment:
      JUPYTER_CONFIG_DIR: '/opt/gitsu_analytics/'       
      JUPYTER_PASSWORD: 'abc123'    
      JUPYTER_ENABLE_LAB: 'yes'
      PYTHONPATH: "${PYTHONPATH}:/opt/gitsu/" # local_settings.py      
      SETTINGS_MODULE: 'local_settings'
