version: '3.1'

services:

  db:
    image: postgres:10.3
    expose:
      - 5432
    volumes:
      - ./postgres:/opt/postgres
    environment:
      # TODO: change this password, currently checked into git
      POSTGRES_PASSWORD: A224697C73DDC7439E35E7272909246D0AB8E5BBE
      POSTGRES_USER: gitsu
      POSTGRES_DB: gitsu
      # Comment these lines to persist data on the local filesystem.
      PGDATA: /opt/postgres/data

  # Service for ETL using Airflow
  gitsu_etl:
    build: 
      context: gitsu_etl/.
      dockerfile: Dockerfile-dev
    volumes:
      - ./gitsu_etl:/opt/gitsu_etl
      - ./:/opt/gitsu_root
    depends_on:
      - db
    environment:
      CONFIG_FILES: 'base.yaml:/opt/gitsu_root/local_settings.yaml'

  # Service for Analytics
  gitsu_analytics:
    build: 
      context: gitsu_analytics/. 
      dockerfile: Dockerfile-dev
    volumes:
      - ./gitsu_analytics:/opt/gitsu_analytics
      - ./:/opt/gitsu_root
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      JUPYTER_CONFIG_DIR: '/opt/gitsu_analytics/'       
      JUPYTER_PASSWORD: 'abc123'    
      JUPYTER_ENABLE_LAB: 'yes'
      CONFIG_FILES: 'base.yaml:/opt/gitsu_root/local_settings.yaml'

  # # Service for Analytics
  # gitsu_web:
  #   build: ./gitsu_web/.
  #   volumes:
  #     - ./gitsu_web/src:/go/src
  #   command: watcher -run main
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   links:
  #     - db
